CREATE USER confluence PASSWORD '6h2tnshDNx7jgdBq';
CREATE DATABASE confluence OWNER confluence CONNECTION LIMIT -1 ENCODING 'UTF8' LC_COLLATE 'en_US.UTF-8' LC_CTYPE 'en_US.UTF-8' TEMPLATE template0;
