services:
  metatube:
    image: ghcr.io/metatube-community/metatube-server
    container_name: metatube
    restart: unless-stopped
    networks:
      - caddy
    env_file: .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone
      - config:/config
    command: ["-dsn", "/config/metatube.db"]

networks:
  caddy:
    name: caddy
    external: true

volumes:
  config:
